# ~/.config/alacritty/alacritty.toml
# Author: Eric Griffith
# http://www.gitlab.com/egriff89

import = [
    # "~/.config/alacritty/themes/themes/doom_one.toml",
    # "~/.config/alacritty/themes/themes/tokyo-night.toml",
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml",
]

[window]
dynamic_padding = false
opacity = 0.95
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[scrolling]
history = 5000

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[colors]
draw_bold_text_with_bright_colors = true

### Key Bindings
[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "L", mods = "Control", action = "ClearLogNotice" },
]
