[tools]
go = "latest"
leiningen = "latest"
clojure = "latest"
opam = "latest"
pnpm = "latest"
uv = "latest"

[settings]
always_keep_download = false
always_keep_install = false
experimental = true
lockfile = true
