[tools]
go = "latest"
leiningen = "latest"
clojure = "latest"
direnv = "latest"
opam = "latest"
pnpm = "latest"
lua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "go"]
always_keep_download = false
always_keep_install = false
